# Site
name: 'Artur Araripe's Blog'
description: 'Boring content creator from Brazil that loves emulators, airplanes and virtual machines.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/mundana-theme-jekyll'
disqus: 'demowebsite'
email: 'arturararipe@protonmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Ara:
      name:           Artur Araripe
      site:           https://www.arturararipe.co.uk
      avatar:         /assets/images/avatar1.jpg
      bio:            "Social Communication/Advertising specialist, focused on product marketing, UI/UX consultancy and community management. I also dabble with virtual planes, emulation, virtualization and music."
      email:          arturararipe@protonmail.com
      twitter:        https://twitter.com/arturararipe
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Ara
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]